## Sale prediction from existing customer - Logistic Regression

In [ ]:
import pandas as pd #useful for loading the dataset
import numpy as np #to perform array operations

## Choose dataset file from Local Directory

In [14]:
from google.colab import files
uploaded = files.upload() 

Saving DigitalAd_dataset.csv to DigitalAd_dataset (3).csv


## Load Dataset

In [16]:
dataset = pd.read_csv('DigitalAd_dataset (3).csv')
print(dataset)

     Age   Salary  Status
0      18   82000       0
1      29   80000       0
2      47   25000       1
3      45   26000       1
4      46   28000       1
..    ...     ...     ...
238    33   25000       1
239    30   73000       0
240    26   74200       1
241    27   36000       0
242    27   12800       0

[243 rows x 3 columns]


## Summarize Dataset

In [17]:
print(dataset.shape)
print(dataset.head(5))

(243, 3)
   Age   Salary  Status
0    18   82000       0
1    29   80000       0
2    47   25000       1
3    45   26000       1
4    46   28000       1


In [18]:
print(dataset.tail(5))

     Age   Salary  Status
238    33   25000       1
239    30   73000       0
240    26   74200       1
241    27   36000       0
242    27   12800       0


## Segregate data into X(Input/Independent Variable) & Y(Output/Dependent Variable)

In [19]:
X = dataset.iloc[:,:-1].values
X

array([[    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    46,  49000],
       [    47,  41000],
       [    49,  22200],
       [    47,  23000],
       [    49,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72200],
       [    67,  31000],
       [    27,  17800],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    46,  49000],
       [    47,  41000],
       [    49,  22200],
       [    47,  23000],
       [    49,  20000],
       [    49,  28000],


In [21]:
Y=dataset.iloc[:,-1].values
Y

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0])

## Splitting dataset into train & test

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.25,random_state=0) #that means 25% data for testing and 75% for training

## Feature Scaling

### We scale our data to make all the features contribute equally to the result                                                                 

### Fit_transform - fit method is calculating the mean and variance of each of the features present in our data

### Transform - Transfrom method is transforming all the features using the respective mean and variance 

### We want our test data to be a completely new and a surprise set for our model

In [27]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
print(X_train)

[[ 5.42554988 -0.01159867]
 [-1.81628058 -0.66279408]
 [-0.40324049 -0.55426151]
 [-0.93313053  3.38908843]
 [-0.5798705  -0.91603673]
 [ 1.0097996  -0.76409114]
 [-0.5798705   1.10990452]
 [ 0.83316959 -0.08395372]
 [ 0.21496455  0.20546646]
 [-0.93313053  1.68874488]
 [ 0.74485458 -0.55426151]
 [-1.72796558  1.3993247 ]
 [ 0.74485458  0.20546646]
 [ 0.83316959 -0.08395372]
 [-0.93313053 -0.44572894]
 [ 1.0097996  -0.62661655]
 [-0.93313053 -0.92327224]
 [-0.5798705   1.10990452]
 [ 1.0097996  -0.84368169]
 [ 0.83316959 -0.48190646]
 [ 0.83316959 -0.48190646]
 [ 0.83316959 -0.48190646]
 [ 0.65653958 -0.62661655]
 [ 0.83316959 -0.66279408]
 [-1.02144553  1.04478498]
 [ 0.65653958 -0.62661655]
 [-0.75650052  1.32696965]
 [ 0.65653958 -0.77132664]
 [ 0.83316959 -0.66279408]
 [-0.93313053  1.68874488]
 [-1.46302056 -0.98839178]
 [-0.84481552  0.02457885]
 [-0.84481552  0.02457885]
 [ 0.83316959 -0.66279408]
 [-1.72796558  1.3993247 ]
 [ 0.92148459 -0.51808399]
 [-0.93313053 -0.92327224]
 

### Training

In [28]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=0)
model.fit(X_train,y_train)

LogisticRegression(random_state=0)

## Predicting whether new customer with user inputted age and salary will buy the product or not

In [30]:
age = int(input("Enter new Customer's Age: "))
sal = int(input("Enter new Customer's Salary : "))
newCust = [[age,sal]]
result= model.predict(sc.transform(newCust))
print(result)
if result == 1:
  print("Customer will Buy ")
else :
  print("Customer will not Buy ")  

Enter new Customer's Age: 56
Enter new Customer's Salary : 1000
[1]
Customer will Buy 


## Prediction for all Test Data

In [32]:
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]]


## Testing accuracy of the model

In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix: ")
print(cm)
print("Accuracy of the model: {0}%".format(accuracy_score(y_test,y_pred)*100))

Confusion Matrix: 
[[29  2]
 [ 8 22]]
Accuracy of the model: 83.60655737704919%
